# Generated by Django 4.1.7 on 2023-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100, unique=True)),
                ('Option1', models.CharField(max_length=30)),
                ('Option2', models.CharField(max_length=30)),
                ('Option3', models.CharField(max_length=30)),
                ('Option4', models.CharField(max_length=30)),
                ('Marks', models.IntegerField(default=0)),
                ('Answer', models.CharField(choices=[('a', models.CharField(max_length=30)), ('b', models.CharField(max_length=30)), ('c', models.CharField(max_length=30)), ('d', models.CharField(max_length=30))], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Marks', models.IntegerField(default=0)),
                ('Time_limit', models.IntegerField(default=0)),
                ('Questions', models.ManyToManyField(to='teacher.question')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams_created', models.ManyToManyField(to='teacher.exam')),
                ('manages', models.ManyToManyField(to='teacher.class')),
                ('qp_created', models.ManyToManyField(to='teacher.questionpaper')),
                ('questions_created', models.ManyToManyField(to='teacher.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='QP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.question'),
        ),
        migrations.AddField(
            model_name='class',
            name='incharge',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
