# Generated by Django 4.1.7 on 2023-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='QP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.questionpaper'),
        ),
    ]
