# Generated by Django 4.1.7 on 2023-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_new',
            name='User_ID',
            field=models.CharField(default='c0f85cf649654c17b18198229999a62c', max_length=100, unique=True),
        ),
    ]
