# Generated by Django 4.1.7 on 2023-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_new_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_new',
            name='User_ID',
            field=models.CharField(default='4669017db0b44d5eb32366228ed91045', max_length=100, unique=True),
        ),
    ]
