# Generated by Django 4.1.7 on 2023-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_instance',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='exam_instance',
            name='exam_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='choices',
            name='ex_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exam_instance'),
        ),
        migrations.AddField(
            model_name='choices',
            name='qs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.question'),
        ),
    ]
